/**
 * VANTA Agent Executor
 *
 * Executes AI agent strategies within the Vanta privacy framework.
 * Agents define trading/DeFi strategies that are encrypted and
 * submitted as intents through the relay network.
 *
 * The executor manages:
 *   - Strategy lifecycle (create, run, pause, stop)
 *   - Execution context with sandboxed state
 *   - Result aggregation and reporting
 *   - Concurrent agent orchestration
 */

import { EventEmitter } from "events";
import { Logger } from "../utils/logger";
import type { IntentParams, IntentResult } from "../core/intent-engine";
import type { Strategy, StrategyConfig, StrategyResult, StrategyContext } from "./strategy";

const logger = new Logger("agent-executor");

// --- Types ---

export interface AgentInstance {
  /** Unique agent identifier */
  id: string;
  /** Display name */
  name: string;
  /** Strategy being executed */
  strategy: Strategy;
  /** Agent configuration */
  config: AgentConfig;
  /** Current execution state */
  state: AgentState;
  /** When the agent was created */
  createdAt: number;
  /** When the agent last ran */
  lastRunAt: number;
  /** Total number of executions */
  executionCount: number;
  /** Number of successful executions */
  successCount: number;
  /** Number of failed executions */
  failureCount: number;
  /** Total intents submitted */
  intentsSubmitted: number;
  /** Total intents executed on-chain */
  intentsExecuted: number;
  /** Cumulative PnL in lamports */
  cumulativePnL: bigint;
  /** Error log (last N errors) */
  errors: Array<{ message: string; timestamp: number }>;
}

export type AgentState =
  | "idle"
  | "running"
  | "paused"
  | "stopping"
  | "stopped"
  | "error";

export interface AgentConfig {
  /** Maximum concurrent intents */
  maxConcurrentIntents: number;
  /** Execution interval (ms) — how often the strategy runs */
  executionIntervalMs: number;
  /** Maximum execution time per run (ms) */
  maxExecutionTimeMs: number;
  /** Whether to auto-restart on failure */
  autoRestart: boolean;
  /** Maximum consecutive failures before stopping */
  maxConsecutiveFailures: number;
  /** Wallet address for this agent */
  walletAddress: string;
  /** Maximum position size in lamports */
  maxPositionLamports: bigint;
  /** Whether this is a dry-run (no actual submissions) */
  dryRun: boolean;
  /** Privacy level for intents */
  privacyLevel: "standard" | "enhanced" | "maximum";
}

export interface ExecutionResult {
  /** Agent ID */
  agentId: string;
  /** Strategy name */
  strategyName: string;
  /** Whether the execution succeeded */
  success: boolean;
  /** Intents generated by this execution */
  intents: IntentParams[];
  /** Results of submitted intents */
  intentResults: IntentResult[];
  /** PnL for this execution (lamports) */
  pnl: bigint;
  /** Execution duration (ms) */
  durationMs: number;
  /** Error message if failed */
  error?: string;
  /** Execution metadata */
  metadata: Record<string, unknown>;
}

export interface ExecutorConfig {
  /** Maximum number of concurrent agents */
  maxAgents: number;
  /** Global execution rate limit (intents per minute) */
  globalRateLimitPerMinute: number;
  /** Whether to enable execution logging */
  enableLogging: boolean;
  /** Maximum error history per agent */
  maxErrorHistory: number;
}

export interface ExecutorMetrics {
  activeAgents: number;
  totalExecutions: number;
  totalIntentsSubmitted: number;
  totalIntentsExecuted: number;
  overallSuccessRate: number;
  totalPnL: bigint;
  averageExecutionTimeMs: number;
}

// --- Default Config ---

const DEFAULT_AGENT_CONFIG: AgentConfig = {
  maxConcurrentIntents: 5,
  executionIntervalMs: 60_000,
  maxExecutionTimeMs: 30_000,
  autoRestart: true,
  maxConsecutiveFailures: 5,
  walletAddress: "",
  maxPositionLamports: 10_000_000_000n, // 10 SOL
  dryRun: false,
  privacyLevel: "enhanced",
};

const DEFAULT_EXECUTOR_CONFIG: ExecutorConfig = {
  maxAgents: 20,
  globalRateLimitPerMinute: 120,
  enableLogging: true,
  maxErrorHistory: 50,
};

// --- Intent Submitter Interface ---

export interface IntentSubmitter {
  submitIntent(params: IntentParams): Promise<IntentResult>;
}

// --- Agent Executor ---

export class AgentExecutor extends EventEmitter {
  private agents: Map<string, AgentInstance> = new Map();
  private executionTimers: Map<string, NodeJS.Timeout> = new Map();
  private config: ExecutorConfig;
  private intentSubmitter: IntentSubmitter;
  private globalIntentCount: number = 0;
  private globalIntentWindowStart: number = Date.now();
  private metrics: ExecutorMetrics = {
    activeAgents: 0,
    totalExecutions: 0,
    totalIntentsSubmitted: 0,
    totalIntentsExecuted: 0,
    overallSuccessRate: 0,
    totalPnL: 0n,
    averageExecutionTimeMs: 0,
  };
  private executionTimeSamples: number[] = [];
  private agentIdCounter: number = 0;

  constructor(
    intentSubmitter: IntentSubmitter,
    config?: Partial<ExecutorConfig>
  ) {
    super();
    this.intentSubmitter = intentSubmitter;
    this.config = { ...DEFAULT_EXECUTOR_CONFIG, ...config };
  }

  /**
   * Register and start a new agent.
   */
  async createAgent(
    name: string,
    strategy: Strategy,
    config?: Partial<AgentConfig>
  ): Promise<AgentInstance> {
    if (this.agents.size >= this.config.maxAgents) {
      throw new ExecutorError(
        `Max agents reached (${this.config.maxAgents})`,
        "MAX_AGENTS"
      );
    }

    const agentConfig = { ...DEFAULT_AGENT_CONFIG, ...config };
    const id = `agent_${++this.agentIdCounter}_${Date.now().toString(36)}`;

    const agent: AgentInstance = {
      id,
      name,
      strategy,
      config: agentConfig,
      state: "idle",
      createdAt: Date.now(),
      lastRunAt: 0,
      executionCount: 0,
      successCount: 0,
      failureCount: 0,
      intentsSubmitted: 0,
      intentsExecuted: 0,
      cumulativePnL: 0n,
      errors: [],
    };

    this.agents.set(id, agent);
    this.updateMetrics();

    this.emit("agentCreated", agent);
    logger.info(
      `Agent created: ${name} (${id}) — strategy: ${strategy.name}, ` +
      `interval: ${agentConfig.executionIntervalMs}ms, ` +
      `dry-run: ${agentConfig.dryRun}`
    );

    return agent;
  }

  /**
   * Start an agent's execution loop.
   */
  async startAgent(agentId: string): Promise<void> {
    const agent = this.getAgentOrThrow(agentId);

    if (agent.state === "running") {
      logger.warn(`Agent ${agentId} already running`);
      return;
    }

    agent.state = "running";
    this.metrics.activeAgents++;

    // Run immediately, then schedule periodic execution
    await this.executeAgent(agent);
    this.scheduleNextExecution(agent);

    this.emit("agentStarted", agent);
    logger.info(`Agent started: ${agent.name} (${agentId})`);
  }

  /**
   * Pause an agent (stops execution but retains state).
   */
  pauseAgent(agentId: string): void {
    const agent = this.getAgentOrThrow(agentId);
    if (agent.state !== "running") return;

    agent.state = "paused";
    this.cancelScheduledExecution(agentId);

    if (this.metrics.activeAgents > 0) {
      this.metrics.activeAgents--;
    }

    this.emit("agentPaused", agent);
    logger.info(`Agent paused: ${agent.name} (${agentId})`);
  }

  /**
   * Resume a paused agent.
   */
  async resumeAgent(agentId: string): Promise<void> {
    const agent = this.getAgentOrThrow(agentId);
    if (agent.state !== "paused") return;

    agent.state = "running";
    this.metrics.activeAgents++;

    await this.executeAgent(agent);
    this.scheduleNextExecution(agent);

    this.emit("agentResumed", agent);
    logger.info(`Agent resumed: ${agent.name} (${agentId})`);
  }

  /**
   * Stop an agent permanently.
   */
  stopAgent(agentId: string): void {
    const agent = this.getAgentOrThrow(agentId);

    agent.state = "stopped";
    this.cancelScheduledExecution(agentId);

    if (this.metrics.activeAgents > 0) {
      this.metrics.activeAgents--;
    }

    this.emit("agentStopped", agent);
    logger.info(
      `Agent stopped: ${agent.name} (${agentId}) — ` +
      `${agent.executionCount} runs, ${agent.intentsSubmitted} intents, ` +
      `PnL: ${agent.cumulativePnL}`
    );
  }

  /**
   * Remove an agent entirely.
   */
  removeAgent(agentId: string): boolean {
    this.stopAgent(agentId);
    return this.agents.delete(agentId);
  }

  /**
   * Get an agent by ID.
   */
  getAgent(agentId: string): AgentInstance | undefined {
    return this.agents.get(agentId);
  }

  /**
   * Get all agents.
   */
  getAllAgents(): AgentInstance[] {
    return [...this.agents.values()];
  }

  /**
   * Get executor metrics.
   */
  getMetrics(): Readonly<ExecutorMetrics> {
    return { ...this.metrics };
  }

  /**
   * Stop all agents.
   */
  stopAll(): void {
    for (const agent of this.agents.values()) {
      if (agent.state === "running" || agent.state === "paused") {
        this.stopAgent(agent.id);
      }
    }
    logger.info("All agents stopped");
  }

  // --- Private ---

  private async executeAgent(agent: AgentInstance): Promise<ExecutionResult> {
    if (agent.state !== "running") {
      return this.emptyResult(agent);
    }

    const startTime = performance.now();
    agent.lastRunAt = Date.now();
    agent.executionCount++;

    // Build execution context
    const context: StrategyContext = {
      agentId: agent.id,
      walletAddress: agent.config.walletAddress,
      maxPositionLamports: agent.config.maxPositionLamports,
      privacyLevel: agent.config.privacyLevel,
      dryRun: agent.config.dryRun,
      executionNumber: agent.executionCount,
      timestamp: Date.now(),
    };

    try {
      // Run strategy
      const strategyResult = await this.runWithTimeout(
        () => agent.strategy.execute(context),
        agent.config.maxExecutionTimeMs
      );

      // Submit intents
      const intentResults: IntentResult[] = [];
      for (const intentParams of strategyResult.intents) {
        if (!this.checkGlobalRateLimit()) {
          logger.warn(`Global rate limit hit, skipping remaining intents`);
          break;
        }

        if (!agent.config.dryRun) {
          try {
            const result = await this.intentSubmitter.submitIntent(intentParams);
            intentResults.push(result);
            agent.intentsSubmitted++;
            this.metrics.totalIntentsSubmitted++;

            if (result.status === "relayed" || result.status === "executed") {
              agent.intentsExecuted++;
              this.metrics.totalIntentsExecuted++;
            }
          } catch (error) {
            logger.warn(
              `Intent submission failed for agent ${agent.id}: ${error}`
            );
          }
        } else {
          logger.debug(
            `[DRY RUN] Would submit: ${intentParams.type} ${intentParams.amount}`
          );
        }
      }

      const durationMs = performance.now() - startTime;
      agent.successCount++;
      agent.cumulativePnL += strategyResult.estimatedPnL;
      this.metrics.totalPnL += strategyResult.estimatedPnL;
      this.recordExecutionTime(durationMs);

      const result: ExecutionResult = {
        agentId: agent.id,
        strategyName: agent.strategy.name,
        success: true,
        intents: strategyResult.intents,
        intentResults,
        pnl: strategyResult.estimatedPnL,
        durationMs,
        metadata: strategyResult.metadata,
      };

      this.metrics.totalExecutions++;
      this.emit("executionComplete", result);

      if (this.config.enableLogging) {
        logger.info(
          `Agent ${agent.name} executed: ${strategyResult.intents.length} intents, ` +
          `PnL: ${strategyResult.estimatedPnL}, duration: ${durationMs.toFixed(0)}ms`
        );
      }

      return result;
    } catch (error) {
      const durationMs = performance.now() - startTime;
      agent.failureCount++;

      const errorMsg = error instanceof Error ? error.message : String(error);
      agent.errors.push({ message: errorMsg, timestamp: Date.now() });
      if (agent.errors.length > this.config.maxErrorHistory) {
        agent.errors = agent.errors.slice(-this.config.maxErrorHistory);
      }

      // Check consecutive failure threshold
      const consecutiveFailures = this.getConsecutiveFailures(agent);
      if (consecutiveFailures >= agent.config.maxConsecutiveFailures) {
        agent.state = "error";
        this.cancelScheduledExecution(agent.id);
        if (this.metrics.activeAgents > 0) {
          this.metrics.activeAgents--;
        }
        logger.error(
          `Agent ${agent.name} stopped after ${consecutiveFailures} consecutive failures`
        );
      }

      const result: ExecutionResult = {
        agentId: agent.id,
        strategyName: agent.strategy.name,
        success: false,
        intents: [],
        intentResults: [],
        pnl: 0n,
        durationMs,
        error: errorMsg,
        metadata: {},
      };

      this.metrics.totalExecutions++;
      this.emit("executionFailed", result);

      logger.error(
        `Agent ${agent.name} execution failed (${durationMs.toFixed(0)}ms): ${errorMsg}`
      );

      return result;
    }
  }

  private scheduleNextExecution(agent: AgentInstance): void {
    this.cancelScheduledExecution(agent.id);

    const timer = setTimeout(async () => {
      if (agent.state === "running") {
        await this.executeAgent(agent);
        this.scheduleNextExecution(agent);
      }
    }, agent.config.executionIntervalMs);

    this.executionTimers.set(agent.id, timer);
  }

  private cancelScheduledExecution(agentId: string): void {
    const timer = this.executionTimers.get(agentId);
    if (timer) {
      clearTimeout(timer);
      this.executionTimers.delete(agentId);
    }
  }

  private async runWithTimeout<T>(
    fn: () => Promise<T>,
    timeoutMs: number
  ): Promise<T> {
    return Promise.race([
      fn(),
      new Promise<never>((_, reject) =>
        setTimeout(
          () => reject(new ExecutorError("Execution timeout", "TIMEOUT")),
          timeoutMs
        )
      ),
    ]);
  }

  private checkGlobalRateLimit(): boolean {
    const now = Date.now();
    if (now - this.globalIntentWindowStart > 60_000) {
      this.globalIntentCount = 0;
      this.globalIntentWindowStart = now;
    }

    if (this.globalIntentCount >= this.config.globalRateLimitPerMinute) {
      return false;
    }

    this.globalIntentCount++;
    return true;
  }

  private getConsecutiveFailures(agent: AgentInstance): number {
    let count = 0;
    for (let i = agent.errors.length - 1; i >= 0; i--) {
      count++;
      // We only have errors, so consecutive failures = recent error count
      // In practice, we'd interleave success markers
    }
    return Math.min(count, agent.failureCount);
  }

  private getAgentOrThrow(agentId: string): AgentInstance {
    const agent = this.agents.get(agentId);
    if (!agent) {
      throw new ExecutorError(`Agent not found: ${agentId}`, "AGENT_NOT_FOUND");
    }
    return agent;
  }

  private recordExecutionTime(ms: number): void {
    this.executionTimeSamples.push(ms);
    if (this.executionTimeSamples.length > 1000) {
      this.executionTimeSamples = this.executionTimeSamples.slice(-500);
    }
    this.metrics.averageExecutionTimeMs =
      this.executionTimeSamples.reduce((a, b) => a + b, 0) /
      this.executionTimeSamples.length;
  }

  private updateMetrics(): void {
    const agents = [...this.agents.values()];
    const totalExec = agents.reduce((s, a) => s + a.executionCount, 0);
    const totalSuccess = agents.reduce((s, a) => s + a.successCount, 0);
    this.metrics.overallSuccessRate = totalExec > 0 ? totalSuccess / totalExec : 0;
  }

  private emptyResult(agent: AgentInstance): ExecutionResult {
    return {
      agentId: agent.id,
      strategyName: agent.strategy.name,
      success: false,
      intents: [],
      intentResults: [],
      pnl: 0n,
      durationMs: 0,
      error: "Agent not running",
      metadata: {},
    };
  }
}

// --- Error class ---

export class ExecutorError extends Error {
  readonly code: string;

  constructor(message: string, code: string = "EXECUTOR_ERROR") {
    super(message);
    this.name = "ExecutorError";
    this.code = code;
  }
}
